version: "3.9"
services:
  shorts:
    build: .
    environment:
      - PYTHONUNBUFFERED=1
    env_file:
      - .env
    volumes:
      - ./outputs:/app/outputs
      - ./secrets:/app/secrets
    command: ["python", "-m", "app.main", "shorts", "--help"]
